#!/usr/bin/env python3
"""Post transparent explanation to Facebook about the auto-posting issue."""
import subprocess, os, json
from pathlib import Path

COMPOSIO = os.path.expanduser("~/.local/bin/composio")
FB_PAGE_ID = "1238353069365061"

# Honest explanation post
explanation = """🛑 TRANSPARENT UPDATE FROM AGENT LAB PH

You may have noticed some posts on this page recently that were:
• Low quality / not fully visible
• Posted automatically without my direct review
• Generated by an experimental AI content system I'm building

I'm Allen, the human behind Agent Lab PH. I'm building an AI automation system that researches, creates, and posts content — but I shipped the "posting" part before the "quality" part was ready. That was my mistake.

WHAT HAPPENED:
- An automated pipeline posted 17 shorts to this page
- Video quality: zoompan on static images, burned captions (not native)
- Some clips had cropping/visibility issues
- I did not personally approve each post before it went live

WHAT I'M DOING ABOUT IT:
1. 🛑 AUTO-POSTING STOPPED — nothing goes live without my explicit approval
2. 🎬 REBUILDING VIDEO QUALITY — switching to Remotion (native React video) for:
   - Native text animations (not burned captions)
   - Proper 9:16 framing with safe zones
   - Smooth transitions, not Ken Burns zoom
   - Professional typography & branding
3. 👁️ HUMAN-IN-THE-LOOP — every post gets my eyes before publish

WHAT YOU'LL SEE NEXT:
- Higher production value
- Native captions that don't get cut off
- Better hooks, cleaner pacing
- Content I actually stand behind

This page is for Filipino freelancers, devs, and BPO folks who want real talk about AI, cloud, and career moves — not AI slop.

Thanks for sticking around. The good stuff is coming.

— Allen
Founder, Agent Lab PH
#AgentLabPH #Transparency #QualityOverQuantity #FilipinoTech"""

def run_composio(args):
    env = dict(os.environ)
    env["PATH"] = os.path.expanduser("~/.composio/bin") + ":" + env["PATH"]
    result = subprocess.run(
        [COMPOSIO] + args, capture_output=True, text=True, timeout=120, env=env
    )
    return result.stdout + result.stderr

# Post to Facebook
fb_args = ["execute", "FACEBOOK_CREATE_POST", "-d", json.dumps({
    "page_id": FB_PAGE_ID,
    "message": explanation,
    "published": True
})]
result = run_composio(fb_args)
print(result)

# Also save to file for reference
Path("/home/allenos/agent-lab-ph/TRANSPARENCY_POST.md").write_text(explanation)
print("\nSaved to TRANSPARENCY_POST.md")